//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class mainlayout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mainlayout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HR.Resource.mainlayout", typeof(mainlayout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air ports.
        /// </summary>
        public static string Air_ports {
            get {
                return ResourceManager.GetString("Air_ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities.
        /// </summary>
        public static string Authorities {
            get {
                return ResourceManager.GetString("Authorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority.
        /// </summary>
        public static string Authority {
            get {
                return ResourceManager.GetString("Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority type.
        /// </summary>
        public static string Authority_type {
            get {
                return ResourceManager.GetString("Authority_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic module.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget.
        /// </summary>
        public static string budget {
            get {
                return ResourceManager.GetString("budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget card.
        /// </summary>
        public static string budget_card {
            get {
                return ResourceManager.GetString("budget_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget class.
        /// </summary>
        public static string budget_class {
            get {
                return ResourceManager.GetString("budget_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget class items.
        /// </summary>
        public static string budget_class_items {
            get {
                return ResourceManager.GetString("budget_class_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cards.
        /// </summary>
        public static string cards {
            get {
                return ResourceManager.GetString("cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check lists.
        /// </summary>
        public static string check_lists {
            get {
                return ResourceManager.GetString("check_lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check lists group.
        /// </summary>
        public static string check_lists_group {
            get {
                return ResourceManager.GetString("check_lists_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check lists items.
        /// </summary>
        public static string check_lists_items {
            get {
                return ResourceManager.GetString("check_lists_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check request.
        /// </summary>
        public static string check_request {
            get {
                return ResourceManager.GetString("check_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check request action.
        /// </summary>
        public static string check_request_action {
            get {
                return ResourceManager.GetString("check_request_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check requistion.
        /// </summary>
        public static string Check_requistion {
            get {
                return ResourceManager.GetString("Check_requistion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check status.
        /// </summary>
        public static string check_status {
            get {
                return ResourceManager.GetString("check_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check type.
        /// </summary>
        public static string check_type {
            get {
                return ResourceManager.GetString("check_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact method.
        /// </summary>
        public static string contact_method {
            get {
                return ResourceManager.GetString("contact_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contract type.
        /// </summary>
        public static string contract_type {
            get {
                return ResourceManager.GetString("contract_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to county.
        /// </summary>
        public static string county {
            get {
                return ResourceManager.GetString("county", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string d {
            get {
                return ResourceManager.GetString("d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.
        /// </summary>
        public static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documents.
        /// </summary>
        public static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documents group.
        /// </summary>
        public static string documents_group {
            get {
                return ResourceManager.GetString("documents_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to education level.
        /// </summary>
        public static string education_level {
            get {
                return ResourceManager.GetString("education_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education title.
        /// </summary>
        public static string education_title {
            get {
                return ResourceManager.GetString("education_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to employee profile group.
        /// </summary>
        public static string employee_profile_group {
            get {
                return ResourceManager.GetString("employee_profile_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee record.
        /// </summary>
        public static string Employee_record {
            get {
                return ResourceManager.GetString("Employee_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee record.
        /// </summary>
        public static string Employee_record_tran {
            get {
                return ResourceManager.GetString("Employee_record_tran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to employee recordes type.
        /// </summary>
        public static string employee_recordes_type {
            get {
                return ResourceManager.GetString("employee_recordes_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to employee transactions.
        /// </summary>
        public static string employee_transactions {
            get {
                return ResourceManager.GetString("employee_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to employee transactions.
        /// </summary>
        public static string employee_transactions_tran {
            get {
                return ResourceManager.GetString("employee_transactions_tran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS.
        /// </summary>
        public static string EOS {
            get {
                return ResourceManager.GetString("EOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS group.
        /// </summary>
        public static string EOS_group {
            get {
                return ResourceManager.GetString("EOS_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS questions groups.
        /// </summary>
        public static string EOS_questions_groups {
            get {
                return ResourceManager.GetString("EOS_questions_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS request.
        /// </summary>
        public static string EOS_request {
            get {
                return ResourceManager.GetString("EOS_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS request.
        /// </summary>
        public static string EOS_request_tran {
            get {
                return ResourceManager.GetString("EOS_request_tran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange rate.
        /// </summary>
        public static string exchange_rate {
            get {
                return ResourceManager.GetString("exchange_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to experience group.
        /// </summary>
        public static string experience_group {
            get {
                return ResourceManager.GetString("experience_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrnal companies.
        /// </summary>
        public static string Extrnal_companies {
            get {
                return ResourceManager.GetString("Extrnal_companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2015 Neon Admin Theme by Laborator.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inquery.
        /// </summary>
        public static string inquery {
            get {
                return ResourceManager.GetString("inquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job level.
        /// </summary>
        public static string job_level {
            get {
                return ResourceManager.GetString("job_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job level card.
        /// </summary>
        public static string job_level_card {
            get {
                return ResourceManager.GetString("job_level_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job level class.
        /// </summary>
        public static string job_level_class {
            get {
                return ResourceManager.GetString("job_level_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job level grade.
        /// </summary>
        public static string job_level_grade {
            get {
                return ResourceManager.GetString("job_level_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job title.
        /// </summary>
        public static string job_title {
            get {
                return ResourceManager.GetString("job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job title card.
        /// </summary>
        public static string job_title_card {
            get {
                return ResourceManager.GetString("job_title_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job title class.
        /// </summary>
        public static string job_title_class {
            get {
                return ResourceManager.GetString("job_title_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job title sub class.
        /// </summary>
        public static string job_title_sub_class {
            get {
                return ResourceManager.GetString("job_title_sub_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miliraty service rank.
        /// </summary>
        public static string miliraty_service_rank {
            get {
                return ResourceManager.GetString("miliraty_service_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miliraty service status.
        /// </summary>
        public static string miliraty_service_status {
            get {
                return ResourceManager.GetString("miliraty_service_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milirty.
        /// </summary>
        public static string milirty {
            get {
                return ResourceManager.GetString("milirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization module.
        /// </summary>
        public static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization chart.
        /// </summary>
        public static string organization_chart {
            get {
                return ResourceManager.GetString("organization_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization chart card.
        /// </summary>
        public static string organization_chart_card {
            get {
                return ResourceManager.GetString("organization_chart_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization unit level.
        /// </summary>
        public static string organization_unit_level {
            get {
                return ResourceManager.GetString("organization_unit_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization unit schema.
        /// </summary>
        public static string organization_unit_schema {
            get {
                return ResourceManager.GetString("organization_unit_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization unit type.
        /// </summary>
        public static string organization_unit_type {
            get {
                return ResourceManager.GetString("organization_unit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization view related to jobs.
        /// </summary>
        public static string organization_view_related_to_jobs {
            get {
                return ResourceManager.GetString("organization_view_related_to_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        public static string personnel {
            get {
                return ResourceManager.GetString("personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personnel transaction.
        /// </summary>
        public static string personnel_transaction {
            get {
                return ResourceManager.GetString("personnel_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string Qulifaication {
            get {
                return ResourceManager.GetString("Qulifaication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qulification category.
        /// </summary>
        public static string Qulification_category {
            get {
                return ResourceManager.GetString("Qulification_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qulification degree.
        /// </summary>
        public static string qulification_degree {
            get {
                return ResourceManager.GetString("qulification_degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qulification main provider.
        /// </summary>
        public static string qulification_main_provider {
            get {
                return ResourceManager.GetString("qulification_main_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qulification name.
        /// </summary>
        public static string qulification_name {
            get {
                return ResourceManager.GetString("qulification_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qulification specialty.
        /// </summary>
        public static string qulification_specialty {
            get {
                return ResourceManager.GetString("qulification_specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qulification sub providor.
        /// </summary>
        public static string qulification_sub_providor {
            get {
                return ResourceManager.GetString("qulification_sub_providor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection_reasons.
        /// </summary>
        public static string Rejection_reasons {
            get {
                return ResourceManager.GetString("Rejection_reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requirments.
        /// </summary>
        public static string requirments {
            get {
                return ResourceManager.GetString("requirments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to responsibilites.
        /// </summary>
        public static string responsibilites {
            get {
                return ResourceManager.GetString("responsibilites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        public static string Risk {
            get {
                return ResourceManager.GetString("Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk type.
        /// </summary>
        public static string Risk_type {
            get {
                return ResourceManager.GetString("Risk_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skill.
        /// </summary>
        public static string skill {
            get {
                return ResourceManager.GetString("skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skills.
        /// </summary>
        public static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skills group.
        /// </summary>
        public static string skills_group {
            get {
                return ResourceManager.GetString("skills_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state/government.
        /// </summary>
        public static string state_government {
            get {
                return ResourceManager.GetString("state_government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscription.
        /// </summary>
        public static string subscription {
            get {
                return ResourceManager.GetString("subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets prices.
        /// </summary>
        public static string Tickets_prices {
            get {
                return ResourceManager.GetString("Tickets_prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        public static string v {
            get {
                return ResourceManager.GetString("v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view jobs.
        /// </summary>
        public static string view_jobs {
            get {
                return ResourceManager.GetString("view_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worklocation.
        /// </summary>
        public static string worklocation {
            get {
                return ResourceManager.GetString("worklocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip postal.
        /// </summary>
        public static string zip_postal {
            get {
                return ResourceManager.GetString("zip_postal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string العربية {
            get {
                return ResourceManager.GetString("العربية", resourceCulture);
            }
        }
    }
}
