//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Medical {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Medical() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HR.Resource.Medical", typeof(Medical).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Allergy Types.
        /// </summary>
        public static string AddNewAllergyTypes {
            get {
                return ResourceManager.GetString("AddNewAllergyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Medical Contribution Allocations Entry.
        /// </summary>
        public static string AddNewMedicalContributionAllocationsEntry {
            get {
                return ResourceManager.GetString("AddNewMedicalContributionAllocationsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Medical Disease.
        /// </summary>
        public static string AddNewMedicalDisease {
            get {
                return ResourceManager.GetString("AddNewMedicalDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Medical Doctor.
        /// </summary>
        public static string AddNewMedicalDoctor {
            get {
                return ResourceManager.GetString("AddNewMedicalDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Medical Doctor Level.
        /// </summary>
        public static string AddNewMedicalDoctorLevel {
            get {
                return ResourceManager.GetString("AddNewMedicalDoctorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Medical medicine classification.
        /// </summary>
        public static string AddNewMedicalmedicineclassification {
            get {
                return ResourceManager.GetString("AddNewMedicalmedicineclassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Medicine.
        /// </summary>
        public static string AddNewMedicine {
            get {
                return ResourceManager.GetString("AddNewMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Sings Symptom.
        /// </summary>
        public static string AddNewSingsSymptom {
            get {
                return ResourceManager.GetString("AddNewSingsSymptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Code.
        /// </summary>
        public static string AllergyCode {
            get {
                return ResourceManager.GetString("AllergyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Name.
        /// </summary>
        public static string AllergyName {
            get {
                return ResourceManager.GetString("AllergyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy TName.
        /// </summary>
        public static string AllergyTName {
            get {
                return ResourceManager.GetString("AllergyTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Types.
        /// </summary>
        public static string AllergyTypes {
            get {
                return ResourceManager.GetString("AllergyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allo./Con. Code.
        /// </summary>
        public static string AlloConCode {
            get {
                return ResourceManager.GetString("AlloConCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed To.
        /// </summary>
        public static string AllowedTo {
            get {
                return ResourceManager.GetString("AllowedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiaries.
        /// </summary>
        public static string Beneficiaries {
            get {
                return ResourceManager.GetString("Beneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Code.
        /// </summary>
        public static string ClassCode {
            get {
                return ResourceManager.GetString("ClassCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification Code.
        /// </summary>
        public static string ClassificationCode {
            get {
                return ResourceManager.GetString("ClassificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con. /Alloc .Code.
        /// </summary>
        public static string ConAlloc_Code {
            get {
                return ResourceManager.GetString("ConAlloc.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con./Alloc. Type Code.
        /// </summary>
        public static string ConAlloc_TypeCode {
            get {
                return ResourceManager.GetString("ConAlloc.TypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraindication.
        /// </summary>
        public static string Contraindication {
            get {
                return ResourceManager.GetString("Contraindication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover For.
        /// </summary>
        public static string CoverFor {
            get {
                return ResourceManager.GetString("CoverFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Allergy Types.
        /// </summary>
        public static string CreateAllergyTypes {
            get {
                return ResourceManager.GetString("CreateAllergyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Medical Contribution Allocations Entry.
        /// </summary>
        public static string CreateMedicalContributionAllocationsEntry {
            get {
                return ResourceManager.GetString("CreateMedicalContributionAllocationsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Medical Disease.
        /// </summary>
        public static string CreateMedicalDisease {
            get {
                return ResourceManager.GetString("CreateMedicalDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Medical Doctor.
        /// </summary>
        public static string CreateMedicalDoctor {
            get {
                return ResourceManager.GetString("CreateMedicalDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Medical Doctor Level.
        /// </summary>
        public static string CreateMedicalDoctorLevel {
            get {
                return ResourceManager.GetString("CreateMedicalDoctorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Medical medicine classification.
        /// </summary>
        public static string CreateMedicalmedicineclassification {
            get {
                return ResourceManager.GetString("CreateMedicalmedicineclassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Medicine.
        /// </summary>
        public static string CreateMedicine {
            get {
                return ResourceManager.GetString("CreateMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sings Symptom.
        /// </summary>
        public static string CreateSingsSymptom {
            get {
                return ResourceManager.GetString("CreateSingsSymptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Code.
        /// </summary>
        public static string DiseaseCode {
            get {
                return ResourceManager.GetString("DiseaseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Name.
        /// </summary>
        public static string DiseaseName {
            get {
                return ResourceManager.GetString("DiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease TName.
        /// </summary>
        public static string DiseaseTName {
            get {
                return ResourceManager.GetString("DiseaseTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor TName.
        /// </summary>
        public static string DoctorTName {
            get {
                return ResourceManager.GetString("DoctorTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Allergy Types.
        /// </summary>
        public static string EditAllergyTypes {
            get {
                return ResourceManager.GetString("EditAllergyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Medical Contribution Allocations Entry.
        /// </summary>
        public static string EditMedicalContributionAllocationsEntry {
            get {
                return ResourceManager.GetString("EditMedicalContributionAllocationsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Medical Disease.
        /// </summary>
        public static string EditMedicalDisease {
            get {
                return ResourceManager.GetString("EditMedicalDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Medical Doctor.
        /// </summary>
        public static string EditMedicalDoctor {
            get {
                return ResourceManager.GetString("EditMedicalDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Medical Doctor Level.
        /// </summary>
        public static string EditMedicalDoctorLevel {
            get {
                return ResourceManager.GetString("EditMedicalDoctorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Medical medicine classification.
        /// </summary>
        public static string EditMedicalmedicineclassification {
            get {
                return ResourceManager.GetString("EditMedicalmedicineclassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Medicine.
        /// </summary>
        public static string EditMedicine {
            get {
                return ResourceManager.GetString("EditMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sings Symptom.
        /// </summary>
        public static string EditSingsSymptom {
            get {
                return ResourceManager.GetString("EditSingsSymptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp Code.
        /// </summary>
        public static string EmpCode {
            get {
                return ResourceManager.GetString("EmpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indication.
        /// </summary>
        public static string Indication {
            get {
                return ResourceManager.GetString("Indication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Contribution.
        /// </summary>
        public static string IsContribution {
            get {
                return ResourceManager.GetString("IsContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Foreign.
        /// </summary>
        public static string IsForeign {
            get {
                return ResourceManager.GetString("IsForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Code.
        /// </summary>
        public static string LevelCode {
            get {
                return ResourceManager.GetString("LevelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Name.
        /// </summary>
        public static string LevelName {
            get {
                return ResourceManager.GetString("LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Contribution Allocations Entry.
        /// </summary>
        public static string MedicalContributionAllocationsEntry {
            get {
                return ResourceManager.GetString("MedicalContributionAllocationsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Disease.
        /// </summary>
        public static string MedicalDisease {
            get {
                return ResourceManager.GetString("MedicalDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Doctor.
        /// </summary>
        public static string MedicalDoctor {
            get {
                return ResourceManager.GetString("MedicalDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Doctor Level.
        /// </summary>
        public static string MedicalDoctorLevel {
            get {
                return ResourceManager.GetString("MedicalDoctorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical medicine classification.
        /// </summary>
        public static string Medicalmedicineclassification {
            get {
                return ResourceManager.GetString("Medicalmedicineclassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Code.
        /// </summary>
        public static string MedicineCode {
            get {
                return ResourceManager.GetString("MedicineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Name.
        /// </summary>
        public static string MedicineName {
            get {
                return ResourceManager.GetString("MedicineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine TName.
        /// </summary>
        public static string MedicineTName {
            get {
                return ResourceManager.GetString("MedicineTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precaultion Warnings.
        /// </summary>
        public static string PrecaultionWarnings {
            get {
                return ResourceManager.GetString("PrecaultionWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Code.
        /// </summary>
        public static string ServiceCode {
            get {
                return ResourceManager.GetString("ServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing Code.
        /// </summary>
        public static string SingCode {
            get {
                return ResourceManager.GetString("SingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing Name.
        /// </summary>
        public static string SingName {
            get {
                return ResourceManager.GetString("SingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sings Symptom.
        /// </summary>
        public static string SingsSymptom {
            get {
                return ResourceManager.GetString("SingsSymptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TName.
        /// </summary>
        public static string TName {
            get {
                return ResourceManager.GetString("TName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usual Dosage.
        /// </summary>
        public static string UsualDosage {
            get {
                return ResourceManager.GetString("UsualDosage", resourceCulture);
            }
        }
    }
}
