//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class organ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal organ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HR.Resource.organ", typeof(organ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new  job title.
        /// </summary>
        public static string add_new_job_title {
            get {
                return ResourceManager.GetString("add_new_job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another row.
        /// </summary>
        public static string addanotherrow {
            get {
                return ResourceManager.GetString("addanotherrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add-education-level.
        /// </summary>
        public static string addeducationlevel {
            get {
                return ResourceManager.GetString("addeducationlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add items.
        /// </summary>
        public static string additems {
            get {
                return ResourceManager.GetString("additems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job level grade.
        /// </summary>
        public static string AddJob_level_grade {
            get {
                return ResourceManager.GetString("AddJob_level_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job level class.
        /// </summary>
        public static string AddJoblevelclass {
            get {
                return ResourceManager.GetString("AddJoblevelclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Authority.
        /// </summary>
        public static string AddNewAuthority {
            get {
                return ResourceManager.GetString("AddNewAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Authority Type.
        /// </summary>
        public static string AddNewAuthorityType {
            get {
                return ResourceManager.GetString("AddNewAuthorityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new budget.
        /// </summary>
        public static string addnewbudget {
            get {
                return ResourceManager.GetString("addnewbudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Budget class.
        /// </summary>
        public static string AddNewBudgetclass {
            get {
                return ResourceManager.GetString("AddNewBudgetclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Budget class item.
        /// </summary>
        public static string AddNewBudgetclassitem {
            get {
                return ResourceManager.GetString("AddNewBudgetclassitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new budget item.
        /// </summary>
        public static string ADDnewbudgetitem {
            get {
                return ResourceManager.GetString("ADDnewbudgetitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Experience group.
        /// </summary>
        public static string AddNewExperiencegroup {
            get {
                return ResourceManager.GetString("AddNewExperiencegroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-new-job-level.
        /// </summary>
        public static string addnewjoblevel {
            get {
                return ResourceManager.GetString("addnewjoblevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New job title class.
        /// </summary>
        public static string AddNewjobtitleclass {
            get {
                return ResourceManager.GetString("AddNewjobtitleclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Job title Sub class.
        /// </summary>
        public static string AddNewJobtitleSubclass {
            get {
                return ResourceManager.GetString("AddNewJobtitleSubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new man power.
        /// </summary>
        public static string addnewmanpower {
            get {
                return ResourceManager.GetString("addnewmanpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Requirment.
        /// </summary>
        public static string AddNewRequirment {
            get {
                return ResourceManager.GetString("AddNewRequirment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Responsibilitie.
        /// </summary>
        public static string AddNewResponsibilitie {
            get {
                return ResourceManager.GetString("AddNewResponsibilitie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Risk.
        /// </summary>
        public static string AddNewRisk {
            get {
                return ResourceManager.GetString("AddNewRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Risks type.
        /// </summary>
        public static string AddNewRiskstype {
            get {
                return ResourceManager.GetString("AddNewRiskstype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Skill.
        /// </summary>
        public static string AddNewSkill {
            get {
                return ResourceManager.GetString("AddNewSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Skill group.
        /// </summary>
        public static string AddNewSkillgroup {
            get {
                return ResourceManager.GetString("AddNewSkillgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New work location.
        /// </summary>
        public static string AddNewworklocation {
            get {
                return ResourceManager.GetString("AddNewworklocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Organization Level Unit.
        /// </summary>
        public static string addOrganizationLevelUnit {
            get {
                return ResourceManager.GetString("addOrganizationLevelUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Organization unit schema.
        /// </summary>
        public static string addOrganizationunitschema {
            get {
                return ResourceManager.GetString("addOrganizationunitschema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Organization unit type.
        /// </summary>
        public static string addOrganizationunittype {
            get {
                return ResourceManager.GetString("addOrganizationunittype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance amount.
        /// </summary>
        public static string Allowanceamount {
            get {
                return ResourceManager.GetString("Allowanceamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterunit Description.
        /// </summary>
        public static string AlterunitDescription {
            get {
                return ResourceManager.GetString("AlterunitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammount forigne.
        /// </summary>
        public static string ammountforigne {
            get {
                return ResourceManager.GetString("ammountforigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount native.
        /// </summary>
        public static string amountnative {
            get {
                return ResourceManager.GetString("amountnative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approved by.
        /// </summary>
        public static string approvedby {
            get {
                return ResourceManager.GetString("approvedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approved Date.
        /// </summary>
        public static string approvedDate {
            get {
                return ResourceManager.GetString("approvedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority.
        /// </summary>
        public static string Authority {
            get {
                return ResourceManager.GetString("Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority Type.
        /// </summary>
        public static string AuthorityType {
            get {
                return ResourceManager.GetString("AuthorityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to index.
        /// </summary>
        public static string backtoindex {
            get {
                return ResourceManager.GetString("backtoindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget classId.
        /// </summary>
        public static string BudgetclassId {
            get {
                return ResourceManager.GetString("BudgetclassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget class items.
        /// </summary>
        public static string Budgetclassitems {
            get {
                return ResourceManager.GetString("Budgetclassitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget details.
        /// </summary>
        public static string budgetdetails {
            get {
                return ResourceManager.GetString("budgetdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget item.
        /// </summary>
        public static string budgetitem {
            get {
                return ResourceManager.GetString("budgetitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget status.
        /// </summary>
        public static string budgetstatus {
            get {
                return ResourceManager.GetString("budgetstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget type.
        /// </summary>
        public static string budgettype {
            get {
                return ResourceManager.GetString("budgettype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget year.
        /// </summary>
        public static string budgetyear {
            get {
                return ResourceManager.GetString("budgetyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cadre code.
        /// </summary>
        public static string cadrecode {
            get {
                return ResourceManager.GetString("cadrecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate added experience years.
        /// </summary>
        public static string Calculateaddedexperienceyears {
            get {
                return ResourceManager.GetString("Calculateaddedexperienceyears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate added military years.
        /// </summary>
        public static string Calculateaddedmilitaryyears {
            get {
                return ResourceManager.GetString("Calculateaddedmilitaryyears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate extra qualification years.
        /// </summary>
        public static string Calculateextraqualificationyears {
            get {
                return ResourceManager.GetString("Calculateextraqualificationyears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancaled by.
        /// </summary>
        public static string cancaledby {
            get {
                return ResourceManager.GetString("cancaledby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancaled Date.
        /// </summary>
        public static string cancaledDate {
            get {
                return ResourceManager.GetString("cancaledDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear all.
        /// </summary>
        public static string clearall {
            get {
                return ResourceManager.GetString("clearall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Authority.
        /// </summary>
        public static string CreateAuthority {
            get {
                return ResourceManager.GetString("CreateAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Authority Type.
        /// </summary>
        public static string CreateAuthorityType {
            get {
                return ResourceManager.GetString("CreateAuthorityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Budget class.
        /// </summary>
        public static string CreateBudgetclass {
            get {
                return ResourceManager.GetString("CreateBudgetclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Budget class item.
        /// </summary>
        public static string CreateBudgetclassitem {
            get {
                return ResourceManager.GetString("CreateBudgetclassitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by.
        /// </summary>
        public static string createdby {
            get {
                return ResourceManager.GetString("createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created Date.
        /// </summary>
        public static string createdDate {
            get {
                return ResourceManager.GetString("createdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Experience group.
        /// </summary>
        public static string CreateExperiencegroup {
            get {
                return ResourceManager.GetString("CreateExperiencegroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job level grade.
        /// </summary>
        public static string CreateJob_level_grade {
            get {
                return ResourceManager.GetString("CreateJob_level_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create job level.
        /// </summary>
        public static string Createjoblevel {
            get {
                return ResourceManager.GetString("Createjoblevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job level class.
        /// </summary>
        public static string CreateJoblevelclass {
            get {
                return ResourceManager.GetString("CreateJoblevelclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create job title class.
        /// </summary>
        public static string Createjobtitleclass {
            get {
                return ResourceManager.GetString("Createjobtitleclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job title Sub class.
        /// </summary>
        public static string CreateJobtitleSubclass {
            get {
                return ResourceManager.GetString("CreateJobtitleSubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create man power.
        /// </summary>
        public static string Createmanpower {
            get {
                return ResourceManager.GetString("Createmanpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new node.
        /// </summary>
        public static string Createnewnode {
            get {
                return ResourceManager.GetString("Createnewnode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Organization Level Unit.
        /// </summary>
        public static string CreateOrganizationLevelUnit {
            get {
                return ResourceManager.GetString("CreateOrganizationLevelUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Organization unit schema.
        /// </summary>
        public static string CreateOrganizationunitschema {
            get {
                return ResourceManager.GetString("CreateOrganizationunitschema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Organization unit type.
        /// </summary>
        public static string CreateOrganizationunittype {
            get {
                return ResourceManager.GetString("CreateOrganizationunittype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Requirment.
        /// </summary>
        public static string CreateRequirment {
            get {
                return ResourceManager.GetString("CreateRequirment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Responsibilitie.
        /// </summary>
        public static string CreateResponsibilitie {
            get {
                return ResourceManager.GetString("CreateResponsibilitie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Risk.
        /// </summary>
        public static string CreateRisk {
            get {
                return ResourceManager.GetString("CreateRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRiskstype.
        /// </summary>
        public static string CreateRiskstype {
            get {
                return ResourceManager.GetString("CreateRiskstype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Skill.
        /// </summary>
        public static string CreateSkill {
            get {
                return ResourceManager.GetString("CreateSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Skill group.
        /// </summary>
        public static string CreateSkillgroup {
            get {
                return ResourceManager.GetString("CreateSkillgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create work location.
        /// </summary>
        public static string Createworklocation {
            get {
                return ResourceManager.GetString("Createworklocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create organization chart.
        /// </summary>
        public static string creatOrganizationchart {
            get {
                return ResourceManager.GetString("creatOrganizationchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency rate.
        /// </summary>
        public static string Currencyrate {
            get {
                return ResourceManager.GetString("Currencyrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dedicated allowence.
        /// </summary>
        public static string dedicated_allowence {
            get {
                return ResourceManager.GetString("dedicated_allowence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEDICATED ALLWANCE VALUE.
        /// </summary>
        public static string DEDICATEDALLWANCEVALUE {
            get {
                return ResourceManager.GetString("DEDICATEDALLWANCEVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default job title sub class.
        /// </summary>
        public static string Defaultjobtitlesubclass {
            get {
                return ResourceManager.GetString("Defaultjobtitlesubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between years must be one year.
        /// </summary>
        public static string Differencebetweenyearsmustbeoneyear {
            get {
                return ResourceManager.GetString("Differencebetweenyearsmustbeoneyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Authority.
        /// </summary>
        public static string EditAuthority {
            get {
                return ResourceManager.GetString("EditAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Authority Type.
        /// </summary>
        public static string EditAuthorityType {
            get {
                return ResourceManager.GetString("EditAuthorityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Budget class.
        /// </summary>
        public static string EditBudgetclass {
            get {
                return ResourceManager.GetString("EditBudgetclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Budget class item.
        /// </summary>
        public static string EditBudgetclassitem {
            get {
                return ResourceManager.GetString("EditBudgetclassitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Experience group.
        /// </summary>
        public static string EditExperiencegroup {
            get {
                return ResourceManager.GetString("EditExperiencegroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT Job_level_grade.
        /// </summary>
        public static string EDITJob_level_grade {
            get {
                return ResourceManager.GetString("EDITJob_level_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit job level.
        /// </summary>
        public static string Editjoblevel {
            get {
                return ResourceManager.GetString("Editjoblevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT Job level class.
        /// </summary>
        public static string EDITJoblevellass {
            get {
                return ResourceManager.GetString("EDITJoblevellass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit job title class.
        /// </summary>
        public static string Editjobtitleclass {
            get {
                return ResourceManager.GetString("Editjobtitleclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Job title Sub class.
        /// </summary>
        public static string EditJobtitleSubclass {
            get {
                return ResourceManager.GetString("EditJobtitleSubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit man power.
        /// </summary>
        public static string Editmanpower {
            get {
                return ResourceManager.GetString("Editmanpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit organization chart.
        /// </summary>
        public static string editOrganizationchart {
            get {
                return ResourceManager.GetString("editOrganizationchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Organization Level Unit.
        /// </summary>
        public static string EditOrganizationLevelUnit {
            get {
                return ResourceManager.GetString("EditOrganizationLevelUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Organization unit schema.
        /// </summary>
        public static string EditOrganizationunitschema {
            get {
                return ResourceManager.GetString("EditOrganizationunitschema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Organization unit type.
        /// </summary>
        public static string EditOrganizationunittype {
            get {
                return ResourceManager.GetString("EditOrganizationunittype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Requirment.
        /// </summary>
        public static string EditRequirment {
            get {
                return ResourceManager.GetString("EditRequirment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Responsibilitie.
        /// </summary>
        public static string EditResponsibilitie {
            get {
                return ResourceManager.GetString("EditResponsibilitie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Risk.
        /// </summary>
        public static string EditRisk {
            get {
                return ResourceManager.GetString("EditRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Risks type.
        /// </summary>
        public static string EditRiskstype {
            get {
                return ResourceManager.GetString("EditRiskstype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Skill.
        /// </summary>
        public static string EditSkill {
            get {
                return ResourceManager.GetString("EditSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Skill group.
        /// </summary>
        public static string EditSkillgroup {
            get {
                return ResourceManager.GetString("EditSkillgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit work location.
        /// </summary>
        public static string Editworklocation {
            get {
                return ResourceManager.GetString("Editworklocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanging ALLWANCE VALUE.
        /// </summary>
        public static string ExchangingALLWANCEVALUE {
            get {
                return ResourceManager.GetString("ExchangingALLWANCEVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forigen.
        /// </summary>
        public static string forign {
            get {
                return ResourceManager.GetString("forign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forign currency.
        /// </summary>
        public static string Forigncurrency {
            get {
                return ResourceManager.GetString("Forigncurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From age.
        /// </summary>
        public static string Fromage {
            get {
                return ResourceManager.GetString("Fromage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frome age bigger than to age.
        /// </summary>
        public static string Fromeagebiggerthantoage {
            get {
                return ResourceManager.GetString("Fromeagebiggerthantoage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from year.
        /// </summary>
        public static string fromyear {
            get {
                return ResourceManager.GetString("fromyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generte slot.
        /// </summary>
        public static string generteslot {
            get {
                return ResourceManager.GetString("generteslot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired.
        /// </summary>
        public static string hired {
            get {
                return ResourceManager.GetString("hired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired-ID.
        /// </summary>
        public static string hiredid {
            get {
                return ResourceManager.GetString("hiredid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        public static string i {
            get {
                return ResourceManager.GetString("i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase number of slots.
        /// </summary>
        public static string increasenumberofslots {
            get {
                return ResourceManager.GetString("increasenumberofslots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job alt-summery.
        /// </summary>
        public static string Job_alt_summery {
            get {
                return ResourceManager.GetString("Job_alt_summery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job level class.
        /// </summary>
        public static string Job_level_class__ID {
            get {
                return ResourceManager.GetString("Job_level_class__ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job level grade.
        /// </summary>
        public static string Job_level_gradeI__D {
            get {
                return ResourceManager.GetString("Job_level_gradeI__D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job Summery.
        /// </summary>
        public static string job_Summery {
            get {
                return ResourceManager.GetString("job_Summery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job-level-linked-to-organization-unit-tipes.
        /// </summary>
        public static string joblevellinkdetoorganizationunittipes {
            get {
                return ResourceManager.GetString("joblevellinkdetoorganizationunittipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Level Setup.
        /// </summary>
        public static string JobLevelSetup {
            get {
                return ResourceManager.GetString("JobLevelSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobs.
        /// </summary>
        public static string jobs {
            get {
                return ResourceManager.GetString("jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title class.
        /// </summary>
        public static string Jobtitleclass {
            get {
                return ResourceManager.GetString("Jobtitleclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title details .
        /// </summary>
        public static string jobtitledetails {
            get {
                return ResourceManager.GetString("jobtitledetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title linked to multi sub-classes.
        /// </summary>
        public static string jobtitlelinkedtomultisubclasses {
            get {
                return ResourceManager.GetString("jobtitlelinkedtomultisubclasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job title Sub class.
        /// </summary>
        public static string jobtitleSubclass {
            get {
                return ResourceManager.GetString("jobtitleSubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOB TYPE ALLWANCE PERCENTAGE.
        /// </summary>
        public static string JOBTYPEALLWANCEPERCENTAGE {
            get {
                return ResourceManager.GetString("JOBTYPEALLWANCEPERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to justification.
        /// </summary>
        public static string justification {
            get {
                return ResourceManager.GetString("justification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k.
        /// </summary>
        public static string kk {
            get {
                return ResourceManager.GetString("kk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Number.
        /// </summary>
        public static string LevelNumber {
            get {
                return ResourceManager.GetString("LevelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        public static string Locationname {
            get {
                return ResourceManager.GetString("Locationname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max annual increase percentage.
        /// </summary>
        public static string max_annual_increase_percentage {
            get {
                return ResourceManager.GetString("max_annual_increase_percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max basic salary.
        /// </summary>
        public static string max_basic_salary {
            get {
                return ResourceManager.GetString("max_basic_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max incentive amount.
        /// </summary>
        public static string max_incentive_amount {
            get {
                return ResourceManager.GetString("max_incentive_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max incentive percentage.
        /// </summary>
        public static string max_incentive_percentage {
            get {
                return ResourceManager.GetString("max_incentive_percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max monthly allowance.
        /// </summary>
        public static string max_monthly_allowance {
            get {
                return ResourceManager.GetString("max_monthly_allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You want delete this data ?.
        /// </summary>
        public static string message_delete {
            get {
                return ResourceManager.GetString("message_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mid basic salary.
        /// </summary>
        public static string mid_basic_salary {
            get {
                return ResourceManager.GetString("mid_basic_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min basic salary.
        /// </summary>
        public static string min_basic_salary {
            get {
                return ResourceManager.GetString("min_basic_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min working years.
        /// </summary>
        public static string min_working_years {
            get {
                return ResourceManager.GetString("min_working_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of educational qualification.
        /// </summary>
        public static string NamEofeducationalqualification {
            get {
                return ResourceManager.GetString("NamEofeducationalqualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native currency.
        /// </summary>
        public static string nativcurrency {
            get {
                return ResourceManager.GetString("nativcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native.
        /// </summary>
        public static string native {
            get {
                return ResourceManager.GetString("native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new basic sallary.
        /// </summary>
        public static string newbasicsallary {
            get {
                return ResourceManager.GetString("newbasicsallary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to num slots.
        /// </summary>
        public static string num_slots {
            get {
                return ResourceManager.GetString("num_slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of direct positions.
        /// </summary>
        public static string numberofdirectpositions {
            get {
                return ResourceManager.GetString("numberofdirectpositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Education.
        /// </summary>
        public static string NumberOfEducation {
            get {
                return ResourceManager.GetString("NumberOfEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of years.
        /// </summary>
        public static string Numberofyears {
            get {
                return ResourceManager.GetString("Numberofyears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string o {
            get {
                return ResourceManager.GetString("o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization chart.
        /// </summary>
        public static string organizationchart {
            get {
                return ResourceManager.GetString("organizationchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization module.
        /// </summary>
        public static string Organizationmodule {
            get {
                return ResourceManager.GetString("Organizationmodule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization unit.
        /// </summary>
        public static string Organizationunit {
            get {
                return ResourceManager.GetString("Organizationunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Unit Level.
        /// </summary>
        public static string OrganizationUnitLevel {
            get {
                return ResourceManager.GetString("OrganizationUnitLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Unit Schema.
        /// </summary>
        public static string OrganizationUnitSchema {
            get {
                return ResourceManager.GetString("OrganizationUnitSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent job.
        /// </summary>
        public static string parentjob {
            get {
                return ResourceManager.GetString("parentjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parent unit code.
        /// </summary>
        public static string parentunitcode {
            get {
                return ResourceManager.GetString("parentunitcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parment.
        /// </summary>
        public static string parment {
            get {
                return ResourceManager.GetString("parment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pervious basic sallary.
        /// </summary>
        public static string perviousbasicsallary {
            get {
                return ResourceManager.GetString("perviousbasicsallary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power plan details.
        /// </summary>
        public static string powerplandetails {
            get {
                return ResourceManager.GetString("powerplandetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print all tree.
        /// </summary>
        public static string printalltree {
            get {
                return ResourceManager.GetString("printalltree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Current Tree.
        /// </summary>
        public static string PrintCurrentTree {
            get {
                return ResourceManager.GetString("PrintCurrentTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification Major.
        /// </summary>
        public static string QualificationMajor {
            get {
                return ResourceManager.GetString("QualificationMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qulifications.
        /// </summary>
        public static string qulifications {
            get {
                return ResourceManager.GetString("qulifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrence number.
        /// </summary>
        public static string Refrencenumber {
            get {
                return ResourceManager.GetString("Refrencenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected by.
        /// </summary>
        public static string Rejectedby {
            get {
                return ResourceManager.GetString("Rejectedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Date.
        /// </summary>
        public static string RejectedDate {
            get {
                return ResourceManager.GetString("RejectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining forigne.
        /// </summary>
        public static string remainingforigne {
            get {
                return ResourceManager.GetString("remainingforigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining native.
        /// </summary>
        public static string Remainingnative {
            get {
                return ResourceManager.GetString("Remainingnative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report job level .
        /// </summary>
        public static string report_job_levelID {
            get {
                return ResourceManager.GetString("report_job_levelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report as ready by.
        /// </summary>
        public static string Reportasreadyby {
            get {
                return ResourceManager.GetString("Reportasreadyby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report as ready Date.
        /// </summary>
        public static string ReportasreadyDate {
            get {
                return ResourceManager.GetString("ReportasreadyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to representation allowance value.
        /// </summary>
        public static string representation_allowance_value {
            get {
                return ResourceManager.GetString("representation_allowance_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibllities.
        /// </summary>
        public static string responsibllities {
            get {
                return ResourceManager.GetString("responsibllities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks.
        /// </summary>
        public static string risks {
            get {
                return ResourceManager.GetString("risks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks Type.
        /// </summary>
        public static string RisksType {
            get {
                return ResourceManager.GetString("RisksType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Authority Type.
        /// </summary>
        public static string SelectAuthorityType {
            get {
                return ResourceManager.GetString("SelectAuthorityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Budget class.
        /// </summary>
        public static string SelectBudgetclass {
            get {
                return ResourceManager.GetString("SelectBudgetclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select-eduction.
        /// </summary>
        public static string selecteduction {
            get {
                return ResourceManager.GetString("selecteduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select-job-level-class.
        /// </summary>
        public static string selectjoblevelclass {
            get {
                return ResourceManager.GetString("selectjoblevelclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select-job-level-grade.
        /// </summary>
        public static string selectjoblevelgrade {
            get {
                return ResourceManager.GetString("selectjoblevelgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select-job-report.
        /// </summary>
        public static string selectjobreport {
            get {
                return ResourceManager.GetString("selectjobreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Job title class.
        /// </summary>
        public static string SelectJobtitleclass {
            get {
                return ResourceManager.GetString("SelectJobtitleclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectloaction.
        /// </summary>
        public static string selectloaction {
            get {
                return ResourceManager.GetString("selectloaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select parent node.
        /// </summary>
        public static string selectparentnode {
            get {
                return ResourceManager.GetString("selectparentnode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Risks Type.
        /// </summary>
        public static string SelectRisksType {
            get {
                return ResourceManager.GetString("SelectRisksType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Skill group.
        /// </summary>
        public static string SelectSkillgroup {
            get {
                return ResourceManager.GetString("SelectSkillgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select unit type code.
        /// </summary>
        public static string selectunittypecode {
            get {
                return ResourceManager.GetString("selectunittypecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill group.
        /// </summary>
        public static string Skillgroup {
            get {
                return ResourceManager.GetString("Skillgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slot.
        /// </summary>
        public static string slot {
            get {
                return ResourceManager.GetString("slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots.
        /// </summary>
        public static string slots {
            get {
                return ResourceManager.GetString("slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special-Allwonce-History.
        /// </summary>
        public static string specialallwance {
            get {
                return ResourceManager.GetString("specialallwance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special requirment.
        /// </summary>
        public static string specialrequirment {
            get {
                return ResourceManager.GetString("specialrequirment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is-no data.
        /// </summary>
        public static string thereisnodata {
            get {
                return ResourceManager.GetString("thereisnodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this code already exists.
        /// </summary>
        public static string thiscodeIsalreadyexists {
            get {
                return ResourceManager.GetString("thiscodeIsalreadyexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this year have already man power you can add your items by enter to edit action and add it.
        /// </summary>
        public static string thisyearhavealreadymanpoweryoucanaddyouritemsbyentertoeditactionandaddit {
            get {
                return ResourceManager.GetString("thisyearhavealreadymanpoweryoucanaddyouritemsbyentertoeditactionandaddit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To age.
        /// </summary>
        public static string Toage {
            get {
                return ResourceManager.GetString("Toage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to year.
        /// </summary>
        public static string toyear {
            get {
                return ResourceManager.GetString("toyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit Description.
        /// </summary>
        public static string unitDescription {
            get {
                return ResourceManager.GetString("unitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit level code.
        /// </summary>
        public static string unitlevelcode {
            get {
                return ResourceManager.GetString("unitlevelcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit type.
        /// </summary>
        public static string unitmail {
            get {
                return ResourceManager.GetString("unitmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit Schema code.
        /// </summary>
        public static string unitSchemacode {
            get {
                return ResourceManager.GetString("unitSchemacode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit state.
        /// </summary>
        public static string unitstate {
            get {
                return ResourceManager.GetString("unitstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type Code.
        /// </summary>
        public static string UnitTypeCode {
            get {
                return ResourceManager.GetString("UnitTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user unit Code.
        /// </summary>
        public static string userunitCode {
            get {
                return ResourceManager.GetString("userunitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacant.
        /// </summary>
        public static string vacant {
            get {
                return ResourceManager.GetString("vacant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validity.
        /// </summary>
        public static string validity {
            get {
                return ResourceManager.GetString("validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view chart.
        /// </summary>
        public static string viewchart {
            get {
                return ResourceManager.GetString("viewchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to working system.
        /// </summary>
        public static string working_system {
            get {
                return ResourceManager.GetString("working_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work location .
        /// </summary>
        public static string worklocationid {
            get {
                return ResourceManager.GetString("worklocationid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can-not delete this row.
        /// </summary>
        public static string youcannotdeletethisRow {
            get {
                return ResourceManager.GetString("youcannotdeletethisRow", resourceCulture);
            }
        }
    }
}
