//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Payroll {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Payroll() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HR.Resource.Payroll", typeof(Payroll).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add All Financial Contract Items.
        /// </summary>
        public static string AddAllFinancialContractItems {
            get {
                return ResourceManager.GetString("AddAllFinancialContractItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Bank.
        /// </summary>
        public static string AddNewBank {
            get {
                return ResourceManager.GetString("AddNewBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Branches.
        /// </summary>
        public static string AddNewBranches {
            get {
                return ResourceManager.GetString("AddNewBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Cost Center Category.
        /// </summary>
        public static string AddNewCostCenterCategory {
            get {
                return ResourceManager.GetString("AddNewCostCenterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Cost Centers.
        /// </summary>
        public static string AddNewCostCenters {
            get {
                return ResourceManager.GetString("AddNewCostCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Employee Financial Contract.
        /// </summary>
        public static string AddNewEmployeeFinancialContract {
            get {
                return ResourceManager.GetString("AddNewEmployeeFinancialContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Extended fields.
        /// </summary>
        public static string AddNewExtendedfields {
            get {
                return ResourceManager.GetString("AddNewExtendedfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Extened Fields Detail.
        /// </summary>
        public static string AddNewExtenedFieldsDetail {
            get {
                return ResourceManager.GetString("AddNewExtenedFieldsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Gl Account Setup.
        /// </summary>
        public static string AddNewGlAccountSetup {
            get {
                return ResourceManager.GetString("AddNewGlAccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Locker.
        /// </summary>
        public static string AddNewLocker {
            get {
                return ResourceManager.GetString("AddNewLocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Manual Payment Types.
        /// </summary>
        public static string AddNewManualPaymentTypes {
            get {
                return ResourceManager.GetString("AddNewManualPaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Payroll Period Setup.
        /// </summary>
        public static string AddNewPayrollPeriodSetup {
            get {
                return ResourceManager.GetString("AddNewPayrollPeriodSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Payroll Transaction Journal Setup.
        /// </summary>
        public static string AddNewPayrollTransactionJournalSetup {
            get {
                return ResourceManager.GetString("AddNewPayrollTransactionJournalSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Salary items collection groups.
        /// </summary>
        public static string AddNewSalaryitemscollectiongroups {
            get {
                return ResourceManager.GetString("AddNewSalaryitemscollectiongroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Description.
        /// </summary>
        public static string AlternativeDescription {
            get {
                return ResourceManager.GetString("AlternativeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code.
        /// </summary>
        public static string BankCode {
            get {
                return ResourceManager.GetString("BankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Choose Bank.
        /// </summary>
        public static string BankCodemustenter {
            get {
                return ResourceManager.GetString("BankCodemustenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Code.
        /// </summary>
        public static string CategoryCode {
            get {
                return ResourceManager.GetString("CategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Choose Category.
        /// </summary>
        public static string CategoryCodemustenter {
            get {
                return ResourceManager.GetString("CategoryCodemustenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check type code.
        /// </summary>
        public static string Checktypecode {
            get {
                return ResourceManager.GetString("Checktypecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check type description.
        /// </summary>
        public static string Checktypedescription {
            get {
                return ResourceManager.GetString("Checktypedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract number.
        /// </summary>
        public static string Contractnumber {
            get {
                return ResourceManager.GetString("Contractnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Centers.
        /// </summary>
        public static string CostCenters {
            get {
                return ResourceManager.GetString("CostCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bank.
        /// </summary>
        public static string CreateBank {
            get {
                return ResourceManager.GetString("CreateBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branches.
        /// </summary>
        public static string CreateBranches {
            get {
                return ResourceManager.GetString("CreateBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Cost Center Category.
        /// </summary>
        public static string CreateCostCenterCategory {
            get {
                return ResourceManager.GetString("CreateCostCenterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Cost Centers.
        /// </summary>
        public static string CreateCostCenters {
            get {
                return ResourceManager.GetString("CreateCostCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Employee Financial Contract.
        /// </summary>
        public static string CreateEmployeeFinancialContract {
            get {
                return ResourceManager.GetString("CreateEmployeeFinancialContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Extended fields.
        /// </summary>
        public static string CreateExtendedfields {
            get {
                return ResourceManager.GetString("CreateExtendedfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Extened Fields Detail.
        /// </summary>
        public static string CreateExtenedFieldsDetail {
            get {
                return ResourceManager.GetString("CreateExtenedFieldsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Gl Account Setup.
        /// </summary>
        public static string CreateGlAccountSetup {
            get {
                return ResourceManager.GetString("CreateGlAccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Locker.
        /// </summary>
        public static string CreateLocker {
            get {
                return ResourceManager.GetString("CreateLocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Manual Payment Types.
        /// </summary>
        public static string CreateManualPaymentTypes {
            get {
                return ResourceManager.GetString("CreateManualPaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Payroll Period Setup.
        /// </summary>
        public static string CreatePayrollPeriodSetup {
            get {
                return ResourceManager.GetString("CreatePayrollPeriodSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Payroll Transaction Journal Setup.
        /// </summary>
        public static string CreatePayrollTransactionJournalSetup {
            get {
                return ResourceManager.GetString("CreatePayrollTransactionJournalSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Salary items collection groups.
        /// </summary>
        public static string CreateSalaryitemscollectiongroups {
            get {
                return ResourceManager.GetString("CreateSalaryitemscollectiongroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Account Fornet.
        /// </summary>
        public static string CreditAccountFornet {
            get {
                return ResourceManager.GetString("CreditAccountFornet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Account Fornet.
        /// </summary>
        public static string DebitAccountFornet {
            get {
                return ResourceManager.GetString("DebitAccountFornet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Salary Code Id.
        /// </summary>
        public static string DefaultSalaryCodeId {
            get {
                return ResourceManager.GetString("DefaultSalaryCodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Type.
        /// </summary>
        public static string DefaultType {
            get {
                return ResourceManager.GetString("DefaultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bank.
        /// </summary>
        public static string EditBank {
            get {
                return ResourceManager.GetString("EditBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Branches.
        /// </summary>
        public static string EditBranches {
            get {
                return ResourceManager.GetString("EditBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cost Center Category.
        /// </summary>
        public static string EditCostCenterCategory {
            get {
                return ResourceManager.GetString("EditCostCenterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cost Centers.
        /// </summary>
        public static string EditCostCenters {
            get {
                return ResourceManager.GetString("EditCostCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Employee Financial Contract.
        /// </summary>
        public static string EditEmployeeFinancialContract {
            get {
                return ResourceManager.GetString("EditEmployeeFinancialContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Extended fields.
        /// </summary>
        public static string EditExtendedfields {
            get {
                return ResourceManager.GetString("EditExtendedfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Extened Fields Detail.
        /// </summary>
        public static string EditExtenedFieldsDetail {
            get {
                return ResourceManager.GetString("EditExtenedFieldsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Gl Account Setup.
        /// </summary>
        public static string EditGlAccountSetup {
            get {
                return ResourceManager.GetString("EditGlAccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Locker.
        /// </summary>
        public static string EditLocker {
            get {
                return ResourceManager.GetString("EditLocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Manual Payment Types.
        /// </summary>
        public static string EditManualPaymentTypes {
            get {
                return ResourceManager.GetString("EditManualPaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Payroll Period Setup.
        /// </summary>
        public static string EditPayrollPeriodSetup {
            get {
                return ResourceManager.GetString("EditPayrollPeriodSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Payroll Transaction Journal Setup.
        /// </summary>
        public static string EditPayrollTransactionJournalSetup {
            get {
                return ResourceManager.GetString("EditPayrollTransactionJournalSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Salary items collection groups.
        /// </summary>
        public static string EditSalaryitemscollectiongroups {
            get {
                return ResourceManager.GetString("EditSalaryitemscollectiongroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Pay Month To Day.
        /// </summary>
        public static string EndPayMonthFromDay {
            get {
                return ResourceManager.GetString("EndPayMonthFromDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Cost Center.
        /// </summary>
        public static string ERPCostCenter {
            get {
                return ResourceManager.GetString("ERPCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Description.
        /// </summary>
        public static string ERPDescription {
            get {
                return ResourceManager.GetString("ERPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended fields code.
        /// </summary>
        public static string Extendedfieldscode {
            get {
                return ResourceManager.GetString("Extendedfieldscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Choose Extended Fields.
        /// </summary>
        public static string ExtendedFieldsCodemustenter {
            get {
                return ResourceManager.GetString("ExtendedFieldsCodemustenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended fields description.
        /// </summary>
        public static string Extendedfieldsdescription {
            get {
                return ResourceManager.GetString("Extendedfieldsdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extened Fields Code.
        /// </summary>
        public static string ExtenedFieldsCode {
            get {
                return ResourceManager.GetString("ExtenedFieldsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extened Fields Detail.
        /// </summary>
        public static string ExtenedFieldsDetail {
            get {
                return ResourceManager.GetString("ExtenedFieldsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Periodic type.
        /// </summary>
        public static string FrequencyPeriodictype {
            get {
                return ResourceManager.GetString("FrequencyPeriodictype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description.
        /// </summary>
        public static string Groupdescription {
            get {
                return ResourceManager.GetString("Groupdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group id.
        /// </summary>
        public static string Groupid {
            get {
                return ResourceManager.GetString("Groupid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        public static string Isactive {
            get {
                return ResourceManager.GetString("Isactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Alternative Description.
        /// </summary>
        public static string JournalAlternativeDescription {
            get {
                return ResourceManager.GetString("JournalAlternativeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Description.
        /// </summary>
        public static string JournalDescription {
            get {
                return ResourceManager.GetString("JournalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal name / Batch code.
        /// </summary>
        public static string Journalname_Batchcode {
            get {
                return ResourceManager.GetString("Journalname_Batchcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Name / Batch Code.
        /// </summary>
        public static string JournalNameBatchCode {
            get {
                return ResourceManager.GetString("JournalNameBatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Type.
        /// </summary>
        public static string JournalType {
            get {
                return ResourceManager.GetString("JournalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Payment Types.
        /// </summary>
        public static string ManualPaymentTypes {
            get {
                return ResourceManager.GetString("ManualPaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Days.
        /// </summary>
        public static string NumberOfDays {
            get {
                return ResourceManager.GetString("NumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type alternative description.
        /// </summary>
        public static string Paymenttypealternativedescription {
            get {
                return ResourceManager.GetString("Paymenttypealternativedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type code.
        /// </summary>
        public static string Paymenttypecode {
            get {
                return ResourceManager.GetString("Paymenttypecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type description.
        /// </summary>
        public static string Paymenttypedescription {
            get {
                return ResourceManager.GetString("Paymenttypedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type source document.
        /// </summary>
        public static string Paymenttypesourcedocument {
            get {
                return ResourceManager.GetString("Paymenttypesourcedocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Alternative Description.
        /// </summary>
        public static string PeriodAlternativeDescription {
            get {
                return ResourceManager.GetString("PeriodAlternativeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Code.
        /// </summary>
        public static string PeriodCode {
            get {
                return ResourceManager.GetString("PeriodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Description.
        /// </summary>
        public static string PeriodDescription {
            get {
                return ResourceManager.GetString("PeriodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Type.
        /// </summary>
        public static string PeriodType {
            get {
                return ResourceManager.GetString("PeriodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose.
        /// </summary>
        public static string Propose {
            get {
                return ResourceManager.GetString("Propose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary code description.
        /// </summary>
        public static string Salarycodedescription {
            get {
                return ResourceManager.GetString("Salarycodedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary code id.
        /// </summary>
        public static string Salarycodeid {
            get {
                return ResourceManager.GetString("Salarycodeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary code type.
        /// </summary>
        public static string Salarycodetype {
            get {
                return ResourceManager.GetString("Salarycodetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary code value.
        /// </summary>
        public static string Salarycodevalue {
            get {
                return ResourceManager.GetString("Salarycodevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary code value type.
        /// </summary>
        public static string Salarycodevaluetype {
            get {
                return ResourceManager.GetString("Salarycodevaluetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary items collection groups.
        /// </summary>
        public static string Salaryitemscollectiongroups {
            get {
                return ResourceManager.GetString("Salaryitemscollectiongroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Items Group.
        /// </summary>
        public static string SalaryItemsGroup {
            get {
                return ResourceManager.GetString("SalaryItemsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bank.
        /// </summary>
        public static string SelectBank {
            get {
                return ResourceManager.GetString("SelectBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Check type code.
        /// </summary>
        public static string SelectChecktypecode {
            get {
                return ResourceManager.GetString("SelectChecktypecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Credit Account Fornet.
        /// </summary>
        public static string SelectCreditAccountFornet {
            get {
                return ResourceManager.GetString("SelectCreditAccountFornet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Debit Account Fornet.
        /// </summary>
        public static string SelectDebitAccountFornet {
            get {
                return ResourceManager.GetString("SelectDebitAccountFornet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Extended Fields.
        /// </summary>
        public static string SelectExtendedFields {
            get {
                return ResourceManager.GetString("SelectExtendedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Extended fields code.
        /// </summary>
        public static string SelectExtendedfieldscode {
            get {
                return ResourceManager.GetString("SelectExtendedfieldscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Journal name Batch code.
        /// </summary>
        public static string SelectJournalname_Batchcode {
            get {
                return ResourceManager.GetString("SelectJournalname_Batchcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Salary Code.
        /// </summary>
        public static string SelectSalaryCode {
            get {
                return ResourceManager.GetString("SelectSalaryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Salary Items Group.
        /// </summary>
        public static string SelectSalaryItemsGroup {
            get {
                return ResourceManager.GetString("SelectSalaryItemsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort index.
        /// </summary>
        public static string Sortindex {
            get {
                return ResourceManager.GetString("Sortindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pay Month From Day.
        /// </summary>
        public static string StartPayMonthFromDay {
            get {
                return ResourceManager.GetString("StartPayMonthFromDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swift Number.
        /// </summary>
        public static string Swiftnumber {
            get {
                return ResourceManager.GetString("Swiftnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Type.
        /// </summary>
        public static string ValueType {
            get {
                return ResourceManager.GetString("ValueType", resourceCulture);
            }
        }
    }
}
