//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class pers_2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pers_2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HR.Resource.pers-2", typeof(pers_2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity number.
        /// </summary>
        public static string Activitynumber {
            get {
                return ResourceManager.GetString("Activitynumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        public static string addedSuccessfully {
            get {
                return ResourceManager.GetString("addedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Element.
        /// </summary>
        public static string addelement {
            get {
                return ResourceManager.GetString("addelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add employee record.
        /// </summary>
        public static string addemployeerecord {
            get {
                return ResourceManager.GetString("addemployeerecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add EOS request.
        /// </summary>
        public static string addEOSRequest {
            get {
                return ResourceManager.GetString("addEOSRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Evalutation Competenies.
        /// </summary>
        public static string addnewevalutationcompetenies {
            get {
                return ResourceManager.GetString("addnewevalutationcompetenies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add personnel transaction.
        /// </summary>
        public static string addpersonneltransaction {
            get {
                return ResourceManager.GetString("addpersonneltransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Questions.
        /// </summary>
        public static string addQ {
            get {
                return ResourceManager.GetString("addQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add request to new contract.
        /// </summary>
        public static string addrequesttonewcontract {
            get {
                return ResourceManager.GetString("addrequesttonewcontract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All record.
        /// </summary>
        public static string allrecord {
            get {
                return ResourceManager.GetString("allrecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by.
        /// </summary>
        public static string Approvedby {
            get {
                return ResourceManager.GetString("Approvedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved date.
        /// </summary>
        public static string Approveddate {
            get {
                return ResourceManager.GetString("Approveddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are The Employee Has A Loan OR Advanced.
        /// </summary>
        public static string aretheemployeehasloanoradvanced {
            get {
                return ResourceManager.GetString("aretheemployeehasloanoradvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are The Settlement Transferred To Payroll.
        /// </summary>
        public static string arethesettlementtransferredtopayroll {
            get {
                return ResourceManager.GetString("arethesettlementtransferredtopayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check_status.
        /// </summary>
        public static string check_status {
            get {
                return ResourceManager.GetString("check_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check List.
        /// </summary>
        public static string checkList {
            get {
                return ResourceManager.GetString("checkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commnets.
        /// </summary>
        public static string Commnets {
            get {
                return ResourceManager.GetString("Commnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contract.
        /// </summary>
        public static string contract {
            get {
                return ResourceManager.GetString("contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract end date.
        /// </summary>
        public static string Contractenddate {
            get {
                return ResourceManager.GetString("Contractenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract information.
        /// </summary>
        public static string contractinformation {
            get {
                return ResourceManager.GetString("contractinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract No..
        /// </summary>
        public static string ContractNo {
            get {
                return ResourceManager.GetString("ContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract start date.
        /// </summary>
        public static string Contractstartdate {
            get {
                return ResourceManager.GetString("Contractstartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create employee record.
        /// </summary>
        public static string Createemployeerecord {
            get {
                return ResourceManager.GetString("Createemployeerecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create EOS Request.
        /// </summary>
        public static string CreateEOSRequest {
            get {
                return ResourceManager.GetString("CreateEOSRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Evaluation Element Competenies.
        /// </summary>
        public static string createEvaluationElementCompetenies1 {
            get {
                return ResourceManager.GetString("createEvaluationElementCompetenies1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Evaluation Grade.
        /// </summary>
        public static string createEvaluationgrade {
            get {
                return ResourceManager.GetString("createEvaluationgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Evaluation Objective.
        /// </summary>
        public static string createEvaluationobjective {
            get {
                return ResourceManager.GetString("createEvaluationobjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Evaluation type.
        /// </summary>
        public static string createEvaluationtype1 {
            get {
                return ResourceManager.GetString("createEvaluationtype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Evalution Questions and Answers.
        /// </summary>
        public static string createevaluitionquestionandanswer {
            get {
                return ResourceManager.GetString("createevaluitionquestionandanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Performance Evaluation Group.
        /// </summary>
        public static string CreatePerformanceEvaluationGroup {
            get {
                return ResourceManager.GetString("CreatePerformanceEvaluationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Personnel Transaction.
        /// </summary>
        public static string CreatePersonnelTransaction {
            get {
                return ResourceManager.GetString("CreatePersonnelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create request to new Contract.
        /// </summary>
        public static string CreaterequesttonewContract {
            get {
                return ResourceManager.GetString("CreaterequesttonewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of EOS.
        /// </summary>
        public static string DateofEOS {
            get {
                return ResourceManager.GetString("DateofEOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of eos interview.
        /// </summary>
        public static string dateofeosinterview {
            get {
                return ResourceManager.GetString("dateofeosinterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of settlement.
        /// </summary>
        public static string dateofsettlement {
            get {
                return ResourceManager.GetString("dateofsettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Type.
        /// </summary>
        public static string Decisiontype {
            get {
                return ResourceManager.GetString("Decisiontype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Degree.
        /// </summary>
        public static string Defaultdegree {
            get {
                return ResourceManager.GetString("Defaultdegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default location.
        /// </summary>
        public static string Defaultlocationdesc {
            get {
                return ResourceManager.GetString("Defaultlocationdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Want Delete This Data?.
        /// </summary>
        public static string deletemessage {
            get {
                return ResourceManager.GetString("deletemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee record.
        /// </summary>
        public static string editemployeerecord1 {
            get {
                return ResourceManager.GetString("editemployeerecord1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit EOS Request.
        /// </summary>
        public static string editEOSRequest {
            get {
                return ResourceManager.GetString("editEOSRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit request to new Contract.
        /// </summary>
        public static string editrequesttonewContract {
            get {
                return ResourceManager.GetString("editrequesttonewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp-ID.
        /// </summary>
        public static string empid {
            get {
                return ResourceManager.GetString("empid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment type.
        /// </summary>
        public static string Employmenttype {
            get {
                return ResourceManager.GetString("Employmenttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp name.
        /// </summary>
        public static string empname {
            get {
                return ResourceManager.GetString("empname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of service date.
        /// </summary>
        public static string Endofservicedate {
            get {
                return ResourceManager.GetString("Endofservicedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS_reasons.
        /// </summary>
        public static string EOS_reasons {
            get {
                return ResourceManager.GetString("EOS_reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS checklist.
        /// </summary>
        public static string EOSchecklist {
            get {
                return ResourceManager.GetString("EOSchecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS-date.
        /// </summary>
        public static string eosdate {
            get {
                return ResourceManager.GetString("eosdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS-interview.
        /// </summary>
        public static string Eosinterview {
            get {
                return ResourceManager.GetString("Eosinterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS type.
        /// </summary>
        public static string EOStype {
            get {
                return ResourceManager.GetString("EOStype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation element.
        /// </summary>
        public static string Evaluationelement {
            get {
                return ResourceManager.GetString("Evaluationelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Element Competenies.
        /// </summary>
        public static string EvaluationElementCompetenies {
            get {
                return ResourceManager.GetString("EvaluationElementCompetenies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Grade.
        /// </summary>
        public static string Evaluationgrade {
            get {
                return ResourceManager.GetString("Evaluationgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation type.
        /// </summary>
        public static string Evaluationtype {
            get {
                return ResourceManager.GetString("Evaluationtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evalution Objective.
        /// </summary>
        public static string evaluitionobjective {
            get {
                return ResourceManager.GetString("evaluitionobjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evalution Questions and Answers.
        /// </summary>
        public static string evaluitionquestionandanswer {
            get {
                return ResourceManager.GetString("evaluitionquestionandanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation element.
        /// </summary>
        public static string Evalutionelement {
            get {
                return ResourceManager.GetString("Evalutionelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Evaluation element.
        /// </summary>
        public static string Evalutionelement1 {
            get {
                return ResourceManager.GetString("Evalutionelement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild.
        /// </summary>
        public static string Faild {
            get {
                return ResourceManager.GetString("Faild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed basic salary by.
        /// </summary>
        public static string Fixed_basic_salary_by {
            get {
                return ResourceManager.GetString("Fixed_basic_salary_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string fromdate {
            get {
                return ResourceManager.GetString("fromdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date Issue bigger date Expire.
        /// </summary>
        public static string FromdateIssuebiggerdateExpire {
            get {
                return ResourceManager.GetString("FromdateIssuebiggerdateExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Score.
        /// </summary>
        public static string Fromscore {
            get {
                return ResourceManager.GetString("Fromscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Score.
        /// </summary>
        public static string fromscore1 {
            get {
                return ResourceManager.GetString("fromscore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation.
        /// </summary>
        public static string interpolation {
            get {
                return ResourceManager.GetString("interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Questions.
        /// </summary>
        public static string InterviewQuestions {
            get {
                return ResourceManager.GetString("InterviewQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title job .
        /// </summary>
        public static string job_descId {
            get {
                return ResourceManager.GetString("job_descId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job level .
        /// </summary>
        public static string Joblevedesc {
            get {
                return ResourceManager.GetString("Joblevedesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Date of work after notice period.
        /// </summary>
        public static string lastDateofworkafternoticeperiod {
            get {
                return ResourceManager.GetString("lastDateofworkafternoticeperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last work day before request.
        /// </summary>
        public static string lastworkdaybeforerequest {
            get {
                return ResourceManager.GetString("lastworkdaybeforerequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last working date.
        /// </summary>
        public static string Lasworkingdate {
            get {
                return ResourceManager.GetString("Lasworkingdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location .
        /// </summary>
        public static string Locationdesc {
            get {
                return ResourceManager.GetString("Locationdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To Make new contract.
        /// </summary>
        public static string makenewcontract {
            get {
                return ResourceManager.GetString("makenewcontract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical commite recomindation.
        /// </summary>
        public static string Medicacommiterecomindation {
            get {
                return ResourceManager.GetString("Medicacommiterecomindation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical information.
        /// </summary>
        public static string medicainformation {
            get {
                return ResourceManager.GetString("medicainformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical commite comments.
        /// </summary>
        public static string Medicalcommitecomments {
            get {
                return ResourceManager.GetString("Medicalcommitecomments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical date.
        /// </summary>
        public static string Medicaldate {
            get {
                return ResourceManager.GetString("Medicaldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical entity name.
        /// </summary>
        public static string Medicalentityname {
            get {
                return ResourceManager.GetString("Medicalentityname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo date.
        /// </summary>
        public static string Memodate {
            get {
                return ResourceManager.GetString("Memodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo number.
        /// </summary>
        public static string Memonumber {
            get {
                return ResourceManager.GetString("Memonumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Answer.
        /// </summary>
        public static string modelanswer {
            get {
                return ResourceManager.GetString("modelanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not fit reason.
        /// </summary>
        public static string Notfireason {
            get {
                return ResourceManager.GetString("Notfireason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice period.
        /// </summary>
        public static string Noticeperiod {
            get {
                return ResourceManager.GetString("Noticeperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice period type.
        /// </summary>
        public static string Noticeperiodtype {
            get {
                return ResourceManager.GetString("Noticeperiodtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Evaluation Group.
        /// </summary>
        public static string PerformanceEvaluationGroup {
            get {
                return ResourceManager.GetString("PerformanceEvaluationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to period.
        /// </summary>
        public static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string periods {
            get {
                return ResourceManager.GetString("periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position status.
        /// </summary>
        public static string Position_status {
            get {
                return ResourceManager.GetString("Position_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position information.
        /// </summary>
        public static string positioninformation {
            get {
                return ResourceManager.GetString("positioninformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position transaction.
        /// </summary>
        public static string Positiontransaction {
            get {
                return ResourceManager.GetString("Positiontransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position transaction information.
        /// </summary>
        public static string positiontransactioninformation {
            get {
                return ResourceManager.GetString("positiontransactioninformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionTransaction number.
        /// </summary>
        public static string PositionTransactionno {
            get {
                return ResourceManager.GetString("PositionTransactionno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionde Scription.
        /// </summary>
        public static string questiondescription {
            get {
                return ResourceManager.GetString("questiondescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended by.
        /// </summary>
        public static string Recommendedby {
            get {
                return ResourceManager.GetString("Recommendedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record amount.
        /// </summary>
        public static string Recordamount {
            get {
                return ResourceManager.GetString("Recordamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record date.
        /// </summary>
        public static string Recorddate {
            get {
                return ResourceManager.GetString("Recorddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record expire date.
        /// </summary>
        public static string Recordexpiredate {
            get {
                return ResourceManager.GetString("Recordexpiredate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record name.
        /// </summary>
        public static string recordname {
            get {
                return ResourceManager.GetString("recordname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record number.
        /// </summary>
        public static string recordnumber {
            get {
                return ResourceManager.GetString("recordnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record value.
        /// </summary>
        public static string Recordvalue {
            get {
                return ResourceManager.GetString("Recordvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove successfully.
        /// </summary>
        public static string removesuccessfully {
            get {
                return ResourceManager.GetString("removesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request-date.
        /// </summary>
        public static string requestdate {
            get {
                return ResourceManager.GetString("requestdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requset date.
        /// </summary>
        public static string Requsetdate {
            get {
                return ResourceManager.GetString("Requsetdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution date.
        /// </summary>
        public static string Resolutiondate {
            get {
                return ResourceManager.GetString("Resolutiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution number.
        /// </summary>
        public static string Resolutionnumber {
            get {
                return ResourceManager.GetString("Resolutionnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist group.
        /// </summary>
        public static string selectedchecklistgroup {
            get {
                return ResourceManager.GetString("selectedchecklistgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS Interview group.
        /// </summary>
        public static string selectedEOSInterviewgroup {
            get {
                return ResourceManager.GetString("selectedEOSInterviewgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        public static string selectedgroup {
            get {
                return ResourceManager.GetString("selectedgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifed_record.
        /// </summary>
        public static string specifidrecord {
            get {
                return ResourceManager.GetString("specifidrecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is Error In Interview.
        /// </summary>
        public static string thereiserrorininterview {
            get {
                return ResourceManager.GetString("thereiserrorininterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string todate {
            get {
                return ResourceManager.GetString("todate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Score.
        /// </summary>
        public static string Toscore {
            get {
                return ResourceManager.GetString("Toscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Score.
        /// </summary>
        public static string toscore1 {
            get {
                return ResourceManager.GetString("toscore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction_Type_.
        /// </summary>
        public static string Transaction_Type_ {
            get {
                return ResourceManager.GetString("Transaction_Type_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction type.
        /// </summary>
        public static string Transactiontype {
            get {
                return ResourceManager.GetString("Transactiontype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit desc.
        /// </summary>
        public static string Unitdesc {
            get {
                return ResourceManager.GetString("Unitdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Current Postion.
        /// </summary>
        public static string viewcurrentpostion {
            get {
                return ResourceManager.GetString("viewcurrentpostion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Competencies.
        /// </summary>
        public static string withcompetencies {
            get {
                return ResourceManager.GetString("withcompetencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Choose Employee.
        /// </summary>
        public static string youmustchooseemployee {
            get {
                return ResourceManager.GetString("youmustchooseemployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Choose Group Of Chick List At First.
        /// </summary>
        public static string youmustchoosegroupofchicklistatfirst {
            get {
                return ResourceManager.GetString("youmustchoosegroupofchicklistatfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Choose Job Title.
        /// </summary>
        public static string youmustchoosejobtitle {
            get {
                return ResourceManager.GetString("youmustchoosejobtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Choose Slot.
        /// </summary>
        public static string youmustchooseslot {
            get {
                return ResourceManager.GetString("youmustchooseslot", resourceCulture);
            }
        }
    }
}
