// <auto-generated />
namespace HR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lfgkfslgjslgs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lfgkfslgjslgs));
        
        string IMigrationMetadata.Id
        {
            get { return "202003271417593_lfgkfslgjslgs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
