//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance_years
    {
        public int ID { get; set; }
        public double Allowance_year { get; set; }
        public double Allowance_percentage { get; set; }
        public double min_Allowance_amount { get; set; }
        public double max_Allowance_amount { get; set; }
    }
}
