//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Append_Public_Holidays_Dates
    {
        public int ID { get; set; }
        public int Public_Holidays_DatesId { get; set; }
        public int Public_Holiday_EventsId { get; set; }
        public System.DateTime Fromdate { get; set; }
        public System.DateTime Todate { get; set; }
        public string Notes { get; set; }
    
        public virtual Public_Holiday_Events Public_Holiday_Events { get; set; }
        public virtual Public_Holidays_Dates Public_Holidays_Dates { get; set; }
    }
}
