//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Append_beneficiary_Family
    {
        public int ID { get; set; }
        public string Family_profile { get; set; }
        public string Family_name { get; set; }
        public int Percentage { get; set; }
        public Nullable<int> Employee_beneficiary_profile_ID { get; set; }
    
        public virtual Employee_beneficiary_profile Employee_beneficiary_profile { get; set; }
    }
}
