//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_Attachment_Profile
    {
        public int ID { get; set; }
        public int Employee_ProfileId { get; set; }
        public string Code { get; set; }
        public bool Is_copy { get; set; }
        public bool Is_required { get; set; }
        public int DocumentsId { get; set; }
        public string DocumentGroup { get; set; }
        public string Issued_place { get; set; }
        public System.DateTime Issue_date { get; set; }
        public System.DateTime Expiry_date { get; set; }
        public string Document_description { get; set; }
        public string Reference_number { get; set; }
        public string Document_number { get; set; }
        public string Comments { get; set; }
        public string Attachmentfile { get; set; }
        public int Related_to { get; set; }
        public int Document_status { get; set; }
        public Nullable<int> Applicant_Profile_ID { get; set; }
    
        public virtual Applicant_Profile Applicant_Profile { get; set; }
        public virtual Document Document { get; set; }
    }
}
