//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_Qualification_Profile
    {
        public int ID { get; set; }
        public string Employee_ProfileId { get; set; }
        public string Code { get; set; }
        public bool Related_to_job { get; set; }
        public System.DateTime Qualification_start_date { get; set; }
        public System.DateTime Qualification_end_date { get; set; }
        public int Years { get; set; }
        public int Months { get; set; }
        public Nullable<int> Educate_categoryId { get; set; }
        public Nullable<int> Educate_TitleId { get; set; }
        public Nullable<int> Main_Educate_bodyId { get; set; }
        public Nullable<int> Sub_educational_bodyId { get; set; }
        public Nullable<int> Name_of_educational_qualificationId { get; set; }
        public Nullable<int> Qualification_MajorId { get; set; }
        public Nullable<int> GradeEducateId { get; set; }
        public int Extra_education_years { get; set; }
        public double Allowance_value { get; set; }
        public Nullable<int> Applicant_Profile_ID { get; set; }
    
        public virtual Applicant_Profile Applicant_Profile { get; set; }
        public virtual Educate_category Educate_category { get; set; }
        public virtual Educate_Title Educate_Title { get; set; }
        public virtual GradeEducate GradeEducate { get; set; }
        public virtual Main_Educate_body Main_Educate_body { get; set; }
        public virtual Name_of_educational_qualification Name_of_educational_qualification { get; set; }
        public virtual Qualification_Major Qualification_Major { get; set; }
        public virtual Sub_educational_body Sub_educational_body { get; set; }
    }
}
