//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budget()
        {
            this.Budget_details = new HashSet<Budget_details>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public int Year_From { get; set; }
        public int Year_To { get; set; }
        public string Organization_unitid { get; set; }
        public int budget_type { get; set; }
        public double Currency_rate { get; set; }
        public double amount_native { get; set; }
        public double ammount_forigne { get; set; }
        public string sign_native { get; set; }
        public string sign_forign { get; set; }
        public double Remaining_native { get; set; }
        public double Remaining_forgin { get; set; }
        public Nullable<int> justification_ID { get; set; }
        public Nullable<int> organization_unit_ID { get; set; }
        public Nullable<int> status_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget_details> Budget_details { get; set; }
        public virtual justification justification { get; set; }
        public virtual Organization_Chart Organization_Chart { get; set; }
        public virtual status status { get; set; }
    }
}
