//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Test_Profile
    {
        public int ID { get; set; }
        public string TryNumber { get; set; }
        public System.DateTime Test_Date { get; set; }
        public string TestCode { get; set; }
        public string TestDescription { get; set; }
        public int Pass_Mark { get; set; }
        public int Full_Mark { get; set; }
        public int Qbtain_Mark { get; set; }
        public string Test_location_Code { get; set; }
        public string Location_Description { get; set; }
        public string Comments { get; set; }
        public int ApplicantId { get; set; }
        public Nullable<int> Application_ID { get; set; }
        public Nullable<int> work_location_ID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual work_location work_location { get; set; }
    }
}
