//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class business_trip_request
    {
        public int ID { get; set; }
        public string number { get; set; }
        public System.DateTime request_date { get; set; }
        public bool carry_important_documents { get; set; }
        public int Employee_ProfileID { get; set; }
        public Nullable<int> Business_TripID { get; set; }
        public System.DateTime go_date { get; set; }
        public System.TimeSpan go_time { get; set; }
        public int TransportationMethodID { get; set; }
        public System.DateTime return_date { get; set; }
        public System.TimeSpan return_time { get; set; }
        public int tionMethodID_return { get; set; }
        public double Total_rate { get; set; }
        public int days { get; set; }
        public int months { get; set; }
        public int years { get; set; }
        public string location_of_duty { get; set; }
        public string purpose_of_duty { get; set; }
        public string Remarks_of_duty { get; set; }
        public int statusID { get; set; }
        public int check_status { get; set; }
    
        public virtual Business_Trip Business_Trip { get; set; }
        public virtual Employee_Profile Employee_Profile { get; set; }
        public virtual status status { get; set; }
        public virtual TransportationMethod TransportationMethod { get; set; }
    }
}
