//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business_Trip()
        {
            this.business_trip_request = new HashSet<business_trip_request>();
        }
    
        public int ID { get; set; }
        public double alloeancereateberdaye { get; set; }
        public Nullable<int> TransportationMethodID { get; set; }
        public Nullable<int> transporation_return_ID { get; set; }
        public string transporation_return_name { get; set; }
        public Nullable<int> ShiftdaystatusID { get; set; }
        public bool linkedtomnothelypayroll { get; set; }
        public bool linkedtomanyalpayment { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Shiftdaystatu Shiftdaystatu { get; set; }
        public virtual TransportationMethod TransportationMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<business_trip_request> business_trip_request { get; set; }
    }
}
