//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_request_change_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public check_request_change_status()
        {
            this.check_Request = new HashSet<check_Request>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public string check_request_statusID { get; set; }
        public int selected_signby { get; set; }
        public int selected_directedto { get; set; }
        public Nullable<int> check_Request_ID { get; set; }
        public Nullable<int> Directed_to_ID { get; set; }
        public Nullable<int> Sign_by_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<check_Request> check_Request { get; set; }
        public virtual check_request_status check_request_status { get; set; }
        public virtual Employee_Profile Employee_Profile { get; set; }
        public virtual Employee_Profile Employee_Profile1 { get; set; }
    }
}
