//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_Lists_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Check_Lists_Items()
        {
            this.check_list_EOS = new HashSet<check_list_EOS>();
        }
    
        public int ID { get; set; }
        public string Check_Code { get; set; }
        public string Description { get; set; }
        public string Description_Alternative { get; set; }
        public bool Is_Mandatory { get; set; }
        public string Check_List_Item_GroupsId { get; set; }
        public Nullable<int> Check_List_Item_Groups_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<check_list_EOS> check_list_EOS { get; set; }
        public virtual Check_List_Item_Groups Check_List_Item_Groups { get; set; }
    }
}
