//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_list_EOS
    {
        public int id { get; set; }
        public bool interpolation { get; set; }
        public Nullable<int> EOS_ID { get; set; }
        public Nullable<int> item_ID { get; set; }
    
        public virtual Check_Lists_Items Check_Lists_Items { get; set; }
        public virtual EOS_Request EOS_Request { get; set; }
    }
}
