//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_contact_profile
    {
        public int ID { get; set; }
        public string Employee_ProfileId { get; set; }
        public string Code { get; set; }
        public bool Primary { get; set; }
        public string ContactmethodsId { get; set; }
        public string Contact_method_detail { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Contact_methods_ID { get; set; }
        public Nullable<int> Employee_Profile_ID { get; set; }
    
        public virtual Contact_methods Contact_methods { get; set; }
        public virtual Employee_Profile Employee_Profile { get; set; }
    }
}
