//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Address_Profile
    {
        public int ID { get; set; }
        public string Employee_ProfileId { get; set; }
        public string Code { get; set; }
        public bool Resident { get; set; }
        public string countryid { get; set; }
        public string areaid { get; set; }
        public string stateid { get; set; }
        public string Territoriesid { get; set; }
        public string citiesid { get; set; }
        public string postcodeId { get; set; }
        public string Streetname { get; set; }
        public int Streetnumber { get; set; }
        public string Pobox { get; set; }
        public int Distancetoworklocationkm { get; set; }
        public int Transportation_method { get; set; }
        public int DistancefromMeetingpointtoworklocationkm { get; set; }
        public Nullable<int> Area_ID { get; set; }
        public Nullable<int> cities_ID { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> Employee_Profile_ID { get; set; }
        public Nullable<int> postcode_ID { get; set; }
        public Nullable<int> Territories_ID { get; set; }
        public Nullable<int> the_states_ID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual city city { get; set; }
        public virtual Country Country { get; set; }
        public virtual Employee_Profile Employee_Profile { get; set; }
        public virtual postcode postcode { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual the_states the_states { get; set; }
    }
}
