//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOS_Interview_Questions_Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EOS_Interview_Questions_Groups()
        {
            this.Definition_of_EOS_Interview_Questions = new HashSet<Definition_of_EOS_Interview_Questions>();
            this.EOS_Request = new HashSet<EOS_Request>();
        }
    
        public int ID { get; set; }
        public string Questions_Group_Code { get; set; }
        public string Description_of { get; set; }
        public string Description_Alternative { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Definition_of_EOS_Interview_Questions> Definition_of_EOS_Interview_Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EOS_Request> EOS_Request { get; set; }
    }
}
