//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOS_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EOS_Request()
        {
            this.Answer_EOS = new HashSet<Answer_EOS>();
            this.check_list_EOS = new HashSet<check_list_EOS>();
        }
    
        public int ID { get; set; }
        public string number { get; set; }
        public System.DateTime Requset_date { get; set; }
        public int EOS_type { get; set; }
        public int Notice_period_type { get; set; }
        public double Notice_period { get; set; }
        public System.DateTime Date_of_EOS { get; set; }
        public System.DateTime last_work_day_before_request { get; set; }
        public System.DateTime last_Date_of_work_after_notice_period { get; set; }
        public bool are_the_employee_has_a_loan_or_advanced { get; set; }
        public bool are_the_settlement_transferred_to_payroll { get; set; }
        public System.DateTime date_of_eos_interview { get; set; }
        public System.DateTime date_of_settlement { get; set; }
        public string note { get; set; }
        public int check_status { get; set; }
        public string sss { get; set; }
        public string req_date { get; set; }
        public string eos_Date { get; set; }
        public int statID { get; set; }
        public string name_state { get; set; }
        public string name_type { get; set; }
        public Nullable<int> Check_List_Item_Groups_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> EOS_group_ID { get; set; }
        public Nullable<int> status_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer_EOS> Answer_EOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<check_list_EOS> check_list_EOS { get; set; }
        public virtual Check_List_Item_Groups Check_List_Item_Groups { get; set; }
        public virtual Employee_Profile Employee_Profile { get; set; }
        public virtual EOS_Interview_Questions_Groups EOS_Interview_Questions_Groups { get; set; }
        public virtual status status { get; set; }
    }
}
