//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evalution_and_competencies
    {
        public int id { get; set; }
        public double Default_degree { get; set; }
        public int EvaluationElementCompeteniesID { get; set; }
        public int EvaluationElementsID { get; set; }
    
        public virtual EvaluationElementCompeteny EvaluationElementCompeteny { get; set; }
        public virtual EvaluationElement EvaluationElement { get; set; }
    }
}
