//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evalu_Element_Tran
    {
        public int ID { get; set; }
        public double H_degree { get; set; }
        public double M_degree { get; set; }
        public double average { get; set; }
        public double final { get; set; }
        public Nullable<int> EvaluationGradeID { get; set; }
        public int EvaluationTransactionID { get; set; }
        public int EvaluationElementsID { get; set; }
    
        public virtual EvaluationElement EvaluationElement { get; set; }
        public virtual EvaluationGrade EvaluationGrade { get; set; }
        public virtual EvaluationTransaction EvaluationTransaction { get; set; }
    }
}
