//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class exper_jobdetails
    {
        public int ID { get; set; }
        public int Job_DetailsID { get; set; }
        public int Experience_groupID { get; set; }
    
        public virtual Experience_group Experience_group { get; set; }
        public virtual Job_Details Job_Details { get; set; }
    }
}
