//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_level_class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job_level_class()
        {
            this.job_level_setup = new HashSet<job_level_setup>();
            this.special_allowance_job_level_class = new HashSet<special_allowance_job_level_class>();
            this.Special_Allwonce_History = new HashSet<Special_Allwonce_History>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double max_monthly_allowance { get; set; }
        public double min_basic_salary { get; set; }
        public double mid_basic_salary { get; set; }
        public double max_basic_salary { get; set; }
        public double min_working_years { get; set; }
        public double max_incentive_amount { get; set; }
        public double max_incentive_percentage { get; set; }
        public double dedicated_allowence { get; set; }
        public double max_annual_increase_percentage { get; set; }
        public double representation_allowance_value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_level_setup> job_level_setup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<special_allowance_job_level_class> special_allowance_job_level_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Special_Allwonce_History> Special_Allwonce_History { get; set; }
    }
}
