//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linked_to_Testing
    {
        public int ID { get; set; }
        public string TestCode { get; set; }
        public string TestDescription { get; set; }
        public System.DateTime Expected_Start_Date { get; set; }
        public System.DateTime Expected_End_Date { get; set; }
        public int Pass_Mark { get; set; }
        public int Full_Mark { get; set; }
        public int Committe_Resolution_RecuirtmentId { get; set; }
    
        public virtual Committe_Resolution_Recuirtment Committe_Resolution_Recuirtment { get; set; }
    }
}
