//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Contributions_Allocations_Services
    {
        public int ID { get; set; }
        public string Medical_Contributions_Allocations_EntryId { get; set; }
        public string Classification_CodeId { get; set; }
        public string Service_CodeId { get; set; }
        public Nullable<int> Medical_Contributions_Allocations_Entry_ID { get; set; }
        public Nullable<int> Medical_Service_ID { get; set; }
        public Nullable<int> Medical_Service_Classification_ID { get; set; }
    
        public virtual Medical_Contributions_Allocations_Entry Medical_Contributions_Allocations_Entry { get; set; }
        public virtual Medical_Service_Classification Medical_Service_Classification { get; set; }
        public virtual Medical_Service Medical_Service { get; set; }
    }
}
