//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel_Committee_Profile
    {
        public int ID { get; set; }
        public string Committe_Resolution_RecuirtmentId { get; set; }
        public string Subject { get; set; }
        public string Activity_Serial_No { get; set; }
        public System.DateTime Committee_Approval_Date { get; set; }
        public int ApplicantId { get; set; }
        public Nullable<int> Application_ID { get; set; }
        public Nullable<int> Committe_Activities_ID { get; set; }
        public Nullable<int> Committe_Resolution_Recuirtment_ID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Committe_Activities Committe_Activities { get; set; }
        public virtual Committe_Resolution_Recuirtment Committe_Resolution_Recuirtment { get; set; }
    }
}
