//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position_Information
    {
        public int ID { get; set; }
        public string Employee_ProfileId { get; set; }
        public string Code { get; set; }
        public bool Primary_Position { get; set; }
        public string job_descId { get; set; }
        public string SlotdescId { get; set; }
        public string Default_location_descId { get; set; }
        public string Location_descId { get; set; }
        public string Job_level_gradeId { get; set; }
        public string Organization_ChartId { get; set; }
        public System.DateTime From_date { get; set; }
        public System.DateTime To_date { get; set; }
        public int Years { get; set; }
        public int Months { get; set; }
        public System.DateTime End_of_service_date { get; set; }
        public System.DateTime Last_working_date { get; set; }
        public string Commnets { get; set; }
        public int working_system { get; set; }
        public int Position_status { get; set; }
        public int EOS_reasons { get; set; }
        public Nullable<int> Employee_Profile_ID { get; set; }
        public Nullable<int> Job_level_grade_ID { get; set; }
        public Nullable<int> job_level_setup_ID { get; set; }
        public Nullable<int> job_title_cards_ID { get; set; }
        public Nullable<int> Organization_Chart_ID { get; set; }
        public Nullable<int> Position_Transaction_Information_ID { get; set; }
        public Nullable<int> work_location_ID { get; set; }
    
        public virtual Employee_Profile Employee_Profile { get; set; }
        public virtual Job_level_grade Job_level_grade { get; set; }
        public virtual job_level_setup job_level_setup { get; set; }
        public virtual job_title_cards job_title_cards { get; set; }
        public virtual Organization_Chart Organization_Chart { get; set; }
        public virtual Position_Transaction_Information Position_Transaction_Information { get; set; }
        public virtual work_location work_location { get; set; }
    }
}
