//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position_Transaction_Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position_Transaction_Information()
        {
            this.Employee_Profile = new HashSet<Employee_Profile>();
            this.Position_Information = new HashSet<Position_Information>();
        }
    
        public int ID { get; set; }
        public string Position_transaction_no { get; set; }
        public System.DateTime Position_transaction { get; set; }
        public int Transaction_Type { get; set; }
        public int Fixed_basic_salary_by { get; set; }
        public string Resolution_number { get; set; }
        public System.DateTime Resolution_date { get; set; }
        public string Activity_number { get; set; }
        public string Memo_number { get; set; }
        public System.DateTime Memo_date { get; set; }
        public string Recommended_by { get; set; }
        public string Approved_by { get; set; }
        public System.DateTime Approved_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Profile> Employee_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position_Information> Position_Information { get; set; }
    }
}
