//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Public_Holidays_Dates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Public_Holidays_Dates()
        {
            this.Append_Public_Holidays_Dates = new HashSet<Append_Public_Holidays_Dates>();
            this.work_location = new HashSet<work_location>();
        }
    
        public int ID { get; set; }
        public string Holidays_Code { get; set; }
        public int Holidaysyear { get; set; }
        public string Holiday_description { get; set; }
        public string Holiday_alternative_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Append_Public_Holidays_Dates> Append_Public_Holidays_Dates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_location> work_location { get; set; }
    }
}
