//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions_Performance
    {
        public int id { get; set; }
        public int PerformanceEvaluationGroupID { get; set; }
        public int EvaluationQuestionsandanswersID { get; set; }
    
        public virtual EvaluationQuestionsandanswer EvaluationQuestionsandanswer { get; set; }
        public virtual PerformanceEvaluationGroup PerformanceEvaluationGroup { get; set; }
    }
}
