//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Question1 { get; set; }
        public string Standart_Question { get; set; }
        public string Filesid { get; set; }
        public Nullable<int> Files_id { get; set; }
        public int TestId { get; set; }
        public string Attachmentfile { get; set; }
    
        public virtual File File { get; set; }
        public virtual Test Test { get; set; }
    }
}
