//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_Information()
        {
            this.Employee_Profile = new HashSet<Employee_Profile>();
        }
    
        public int ID { get; set; }
        public string Pension { get; set; }
        public string Pension_source { get; set; }
        public System.DateTime EOS_date { get; set; }
        public bool Have_pension { get; set; }
        public System.DateTime Retired_expected_EOS { get; set; }
        public System.DateTime Last_working_date { get; set; }
        public string CurrencyId { get; set; }
        public bool Is_merits_The_date_of_death { get; set; }
        public Nullable<int> Currency_ID { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Profile> Employee_Profile { get; set; }
    }
}
