//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift_setup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shift_setup()
        {
            this.Schedule_Details = new HashSet<Schedule_Details>();
            this.Shiftdaystatus = new HashSet<Shiftdaystatu>();
        }
    
        public int ID { get; set; }
        public int working_system { get; set; }
        public int Total_Hours { get; set; }
        public System.TimeSpan Start_time { get; set; }
        public System.TimeSpan End_time { get; set; }
        public Nullable<int> Weekend_setupID { get; set; }
        public Nullable<int> work_locationID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_Details> Schedule_Details { get; set; }
        public virtual Weekend_setup Weekend_setup { get; set; }
        public virtual work_location work_location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shiftdaystatu> Shiftdaystatus { get; set; }
    }
}
