//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sings_Symptom
    {
        public int ID { get; set; }
        public double Sing_Code { get; set; }
        public string Sing_Name { get; set; }
        public string Notes { get; set; }
    }
}
