//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public int ID { get; set; }
        public string slot_code { get; set; }
        public string slot_description { get; set; }
        public string joblevelsetupID { get; set; }
        public int check_status { get; set; }
        public int slot_type { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> Employee_Profile_ID { get; set; }
        public Nullable<int> job_level_setup_ID { get; set; }
        public Nullable<int> job_title_cards_ID { get; set; }
        public Nullable<int> Organization_Chart___ID { get; set; }
    
        public virtual Employee_Profile Employee_Profile { get; set; }
        public virtual job_level_setup job_level_setup { get; set; }
        public virtual job_title_cards job_title_cards { get; set; }
        public virtual Organization_Chart Organization_Chart { get; set; }
    }
}
