//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public status()
        {
            this.Budgets = new HashSet<Budget>();
            this.business_trip_request = new HashSet<business_trip_request>();
            this.Committe_Resolution_Recuirtment = new HashSet<Committe_Resolution_Recuirtment>();
            this.Employee_records = new HashSet<Employee_records>();
            this.EOS_Request = new HashSet<EOS_Request>();
            this.EvaluationTransactions = new HashSet<EvaluationTransaction>();
            this.Exit_permission_request = new HashSet<Exit_permission_request>();
            this.man_power = new HashSet<man_power>();
            this.personnel_transaction = new HashSet<personnel_transaction>();
            this.request_new_contract = new HashSet<request_new_contract>();
            this.workpermissionrequests = new HashSet<workpermissionrequest>();
        }
    
        public int ID { get; set; }
        public int statu { get; set; }
        public string created_by { get; set; }
        public string return_to_reviewby { get; set; }
        public string approved_by { get; set; }
        public string Rejected_by { get; set; }
        public string cancaled_by { get; set; }
        public System.DateTime created_bydate { get; set; }
        public System.DateTime return_to_reviewdate { get; set; }
        public System.DateTime approved_bydate { get; set; }
        public System.DateTime Rejected_bydate { get; set; }
        public System.DateTime cancaled_bydate { get; set; }
        public int Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget> Budgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<business_trip_request> business_trip_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Committe_Resolution_Recuirtment> Committe_Resolution_Recuirtment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_records> Employee_records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EOS_Request> EOS_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationTransaction> EvaluationTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exit_permission_request> Exit_permission_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<man_power> man_power { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_transaction> personnel_transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_new_contract> request_new_contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workpermissionrequest> workpermissionrequests { get; set; }
    }
}
