//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription_Syndicate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription_Syndicate()
        {
            this.Applicant_Subscription_Syndicate_Profile = new HashSet<Applicant_Subscription_Syndicate_Profile>();
            this.Employee_subscription_syndicate_profile = new HashSet<Employee_subscription_syndicate_profile>();
        }
    
        public int ID { get; set; }
        public bool Server_Legatees { get; set; }
        public string Subscription_Code { get; set; }
        public string Subscription_Description { get; set; }
        public string Subscription_Alternative_Description { get; set; }
        public string Contact_Detail { get; set; }
        public int Default_Subscription_Fees { get; set; }
        public int Deduction_Period { get; set; }
        public int Type { get; set; }
        public string Phone_1 { get; set; }
        public string Phone_2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Contact_methodsId { get; set; }
        public Nullable<int> Contact_methods_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant_Subscription_Syndicate_Profile> Applicant_Subscription_Syndicate_Profile { get; set; }
        public virtual Contact_methods Contact_methods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_subscription_syndicate_profile> Employee_subscription_syndicate_profile { get; set; }
    }
}
