//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models.penalities.setup
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Discipline_PunishmentTransaction")]
    public  class Discipline_PunishmentTransaction
    {
        public int ID { get; set; }
        [Required(ErrorMessageResourceType = typeof(HR.Resource.Basic), ErrorMessageResourceName = "error_message")]
        [StringLength(50)]
        [Index(IsUnique = true)]
        public string Transaction_Number { get; set; }
        [Required(ErrorMessageResourceType = typeof(HR.Resource.Basic), ErrorMessageResourceName = "error_message")]
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        [Required(ErrorMessageResourceType = typeof(HR.Resource.Basic), ErrorMessageResourceName = "error_message")]
        public Nullable<System.DateTime> Event_Date { get; set; }
        [Required(ErrorMessageResourceType = typeof(HR.Resource.Basic), ErrorMessageResourceName = "error_message")]
        public string Employee_Code { get; set; }
        public string em { get; set; }
        public string Transaction_Statement { get; set; }
        public Nullable<bool> Custom_Rest { get; set; }
        public string RestOption_Code { get; set; }
        public Nullable<System.DateTime> RestOption_Date { get; set; }
        public Nullable<short> Transaction_Status { get; set; }
        //===================================================================
        public string ReportAsReadyBy { get; set; }
        public Nullable<System.DateTime> ReportAsReadyDate { get; set; }
        public string ReportAsReady_Comment { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Approved_Comment { get; set; }
        public string RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public string Rejected_Comment { get; set; }
        public string CanceledBy { get; set; }
        public Nullable<System.DateTime> CanceledDate { get; set; }
        public string Canceled_Comment { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string Closed_Comment { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string Posted_Comment { get; set; }
        public string Company_ID { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public int RowIndx { get; set; }
        public virtual status stat { get; set; }
        public int stat_ID { get; set; }
        public bool Posted_to_payroll { get; set; }
    }
}
